[package]
name = "multitap-core"
version = "0.0.1"
authors = ["yusakufujikifr"]
edition = "2018"

[dependencies]
log = "0.4"

serde = "~1.0.123"
serde_derive = "~1.0.123"
ron = "~0.6.4"
structopt = "~0.3.21"
serde_json = "1.0"

multitap-core-evdev = { path = "../multitap-core-evdev" }