[package]
name = "multitap-core-evdev"
version = "0.0.1"
authors = ["yusakufujikifr"]
edition = "2018"

[dependencies]
serde = "~1.0.123"
serde_derive = "~1.0.123"
evdev-sys = { path = "../../evdev-rs/evdev-sys" }
nix = "~0.19.1"
